#!/usr/bin/env bash

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

git config --global user.email "rinsanga1221@gmail.com"
git config --global user.name "Rinsanga1"

cargo install stylua

pushd /tmp/luarocks-3.11.0
(
    wget --output-document /tmp/luarocks.tar.gz https://luarocks.org/releases/luarocks-3.11.0.tar.gz
    tar zxpf /tmp/luarocks.tar.gz -C /tmp
    cd
    ./configure && make && sudo make install
)
popd

luarocks install luacheck

